Fixes escape of \t and \r
microsoft/kiota-serialization-json-go pull request #34
Opened 2022-07-11 15:48 UTC by dadams39

Fixes for Issue #30 
- Did not add any tests. Passes all current tests. I used a file to upload a full file with \r and \t to ensure that a valid json was output.

2022-07-11 16:46 UTC, baywet requested changes
Thanks for the contribution.
Can you add test cases please?
Can you add an entry the changelog please? (you can take 0.5.5, and date it from today)

2022-07-11 16:46 UTC, baywet commented on json_serialization_writer.go
> +	value = strings.ReplaceAll(strings.ReplaceAll(value, "\t", ""), "\r", "")
```suggestion
	value = strings.ReplaceAll(strings.ReplaceAll(value, "\t", "\\t"), "\r", "\\r")
```

(and move this below the next one so it doesn't end up escaping the \ multiple times)

2022-07-11 21:28 UTC, dadams39 commented
Test Suite and Changelog updated.

2022-07-12 12:54 UTC, baywet approved these changes
Thanks a lot for the continuous conversation and the contribution!

2022-07-12 12:55 UTC, merged